<?xml version="1.0" encoding="utf-8"?>
<Root>
  <resultFlag>0</resultFlag>
  <failCode>C18</failCode>
  <failInfo><![CDATA[C:\ImpPath\Npts\OutBox\20191126161138__QDI0000201911211003403933.xml错误信息：RabbitMQ 发送报文时发生错误,连接:amqp://U_SW3241Dgsd:[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9iBUX73I1y7V+6YPlCvQUAz/iCe2Wj/agNZeV3KQ==]@219.142.41.236:5671/V_SW3241Dgsd, SSL:True, RoutingKey:Q_SendSW3241Dgsd, Exchange:, 错误：The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text="Unexpected Exception", classId=0, methodId=0, cause=System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   在 RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   在 RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   在 RabbitMQ.Client.Framing.Impl.Connection.MainLoop()]]></failInfo>
  <retData></retData>
</Root>